### ISSUE TITLE
Long term goal?

### ISSUE THREAD

**Issue by shaun-sweet** [nikitavoloboev/learn-anything#1006]
This seems cool.  I just worry that it doesn't have much future if its one person that has to update EVERY learning path?  Any thoughts on having the maps community sourced?  Its just not plausible that one person can make learning path changes to everything there is to learn.

**Comment by nikitavoloboev** [comment]
We are working on changing our mind map render to use D3.js and with it we plan to ease contributions greatly. Anyone can change the mind maps and integrate changes or create mind maps of their own and propose for them to be added to search engine. 

So no, I won't be doing it alone. It's a community project similar to awesome lists but on a broader scale and in a unique and visual format focused on learning in a linear way. :)
