### ISSUE TITLE
best path for learning android programming

### ISSUE THREAD

**Issue by sukhbir-singh** [nikitavoloboev/learn-anything#1026]
Documentation:-
https://developer.android.com/training/index.html

Other tutorials:-
www.vogella.com/tutorials/android.html

Video tutorials:-
https://www.udacity.com/course/android-development-for-beginners--ud837
https://www.udacity.com/course/developing-android-apps--ud853
https://www.udacity.com/course/advanced-android-app-development--ud855
https://www.udacity.com/course/android-basics-multiscreen-apps--ud839

**Comment by nikitavoloboev** [comment]
Thank you a lot @sukhbir-singh, I have added it.
