### ISSUE TITLE
Links need to open in new tab

### ISSUE THREAD

**Issue by sukhbir-singh** [nikitavoloboev/learn-anything#1052]
I feel their is a need of opening links for each graph link in new tab by default. That is, whenever a user searches on learn-anything.xyz a graph is shown with useful links as nodes. On clicking on that node, right now the site opens in same tab only but in my perspective it should open in new tab so that user can click on more links without coming back and forth on graph.

Let me know about your opinion about same.

**Comment by nikitavoloboev** [comment]
Hey @sukhbir-singh. Yeah I agree with you, perhaps it will be good to open new tabs in a new tab. 

Although I do dislike leaving a browser tab with the search open every time you go to a link. For example with Google, going to a link will open the link in the current tab. Cmd + clicking it will open it in a new tab. We have to fix cmd + clicking on our end but if we fix that, will it work for you? 

Or you still prefer having all links be opened in a new tab?

**Comment by sukhbir-singh** [comment]
As I am using fedora linux and chrome browser, ctrl + mouse click should open the link in new tab but presently the link gets opened in current tab only.

**Comment by nikitavoloboev** [comment]
This will be included in our next big update @sukhbir-singh :)
