### ISSUE TITLE
Request to Fix the Page Zoom and Anchor!

### ISSUE THREAD

**Issue by Mahelaa** [nikitavoloboev/learn-anything#1058]
Hey i discovered this amazing search engine from your comment on reddit and its an amazing tool for people that are interested in learning. But i do have a few issues/gripes that i would like to bring to your attention and hopefully you could fix :)
1. **Zoom Lock.** 
This is one of the main issues i have atm. That is the fact that you can infinitely zoom into the page. It would be great to have it at a fixed position so that we could not go beyond the required limit. The best example for how this is a hinderance is when i try to scroll and miss the bar and instead keep zooming into the page
2. **Please anchor the tree to the center or a fixed point**
Another thing is the ability to mov, i take this as nothing severe and is mostly because of my preferences. but it would be great if the tree was in a fixed position

Again these are minor details. 
If you would like any help, i would be gladly willing to contribute

Thanks for your work :D 
Good Luck

**Comment by nikitavoloboev** [comment]
Hey @Mahelaa. Thank you a lot for the kind comment. :)

We are currently in process of moving [render](https://github.com/learn-anything/react-mindmap) to [D3.js](https://github.com/d3/d3). This will fix panning and will also make moving around the map a lot smoother especially on mobile.

As far as zoom lock, you are right. We will restrict how much a person can zoom in and out so to make UX of using the maps as best as it can be.

For point 2. I myself wish all maps would start with a fixed position too no matter how much you zoomed in/out in previous map and I hope that will come with the next update too which is genuinely quite exciting. 

If you want to help. You can join [our active slack group](https://knowledge-map.slack.com/shared_invite/MTgxNTYzMjIzNjM5LTE0OTQzMzA4MDAtYzY1YWY0ZDc0NQ). 💙

**Comment by nikitavoloboev** [comment]
This will be fixed in our next big upcoming update 🎊
