### ISSUE TITLE
Blog's https is not secure

### ISSUE THREAD

**Issue by jlrg1992** [nikitavoloboev/learn-anything#1059]
Images in the blog are not taken in https but from http sources. I know maybe is not the biggest problem, but it is an easy fix.

**Comment by nikitavoloboev** [comment]
Thank you @jlrg1992. You are right, we will change everything to https now. :)

**Comment by nikitavoloboev** [comment]
I actually checked now and images are being taken from GitHub which uses https. What images are referring too?

**Comment by jlrg1992** [comment]
Right here. You're taking them from github but you're not using https That's why it doesn´t say it is a secure website
![captura de pantalla 2017-06-17 a la s 18 30 30](https://user-images.githubusercontent.com/19863398/27256949-52ee0664-538b-11e7-8d13-348d687c8914.png)

**Comment by nikitavoloboev** [comment]
We are now using [wiki](https://github.com/nikitavoloboev/learn-anything/wiki) for documentation so this problem should go away. :)
