### ISSUE TITLE
The resources do not want to open in a new tab

### ISSUE THREAD

**Issue by yvan-sraka** [nikitavoloboev/learn-anything#1060]
When I try to open a link by holding down the `Ctrl` key on Mozilla Firefox, the link does not open in a new tab as the desired behavior.

**Comment by nikitavoloboev** [comment]
Yeah sorry about this. This will be fixed in the new update coming very soon.

**Comment by nikitavoloboev** [comment]
@yvan-sraka they open in new tab now by default, I hope you like this :)
