### ISSUE TITLE
open from opera mini

### ISSUE THREAD

**Issue by mzaini30** [nikitavoloboev/learn-anything#1061]
can i access it from opera mini?

**Comment by nikitavoloboev** [comment]
I don't have opera mini to test it so not sure. Have you tried it and it doesn't work

**Comment by mzaini30** [comment]
i've open it in my galaxy young (opera mini browser). i just get input text without submit button

**Comment by nikitavoloboev** [comment]
Sorry about this, I think we know what the issue is. Will be fixed in next update. 🎊

**Comment by Katamori** [comment]
Oh yes, browsers without or with limited JS functionality may not display the site properly.

Tried on an acient version of Opera Mobile (12.10), same error. At least here I get the suggestion menu, but selecting any from it has no effect.

**Comment by mzaini30** [comment]
thanks friend

**Comment by Katamori** [comment]
This issue is going to come a long way, though; ancient browsers are rarely if ever suitable for such one-page applications.
