### ISSUE TITLE
No maps are displayed when using Edge browser

### ISSUE THREAD

**Issue by malaclypse** [nikitavoloboev/learn-anything#1062]
No maps are displayed when using Edge browser. See the attached screenshot. 
![edge issue](https://user-images.githubusercontent.com/5909968/27086851-2062aeb6-505c-11e7-87d4-97bb497cc044.png)

**Comment by Katamori** [comment]
What the-

**Comment by nikitavoloboev** [comment]
Sorry about this. Will try to fix this in the next update.

**Comment by jr-duboc** [comment]
It looks like this is also the case on Chrome for Windows 7. Maybe it's relate ?

**Comment by nikitavoloboev** [comment]
Moved this issue to [search engine repo](https://github.com/learn-anything/search-engine)

**Comment by nikitavoloboev** [comment]
are there any errors in the console? @malaclypse
