### ISSUE TITLE
Adding "programming principles" or "methods"

### ISSUE THREAD

**Issue by Katamori** [nikitavoloboev/learn-anything#1064]
Not exactly sure where would it fit, but definitely means a huge area within programming and absolutely worthy for a map on its own.

**Comment by nikitavoloboev** [comment]
Yeah certainly. Will add it to software dev. :)

**Comment by nikitavoloboev** [comment]
Actually I am not sure how I would add this. What would you add exactly under it? I mean I have lots of things included already in software dev (testing, devops ..)

Where would this fit in?

**Comment by Katamori** [comment]
I think it'd fit to "programming" easily.

**Comment by nikitavoloboev** [comment]
Let's discuss this in our Slack group, as I am still not sure how to best add programming methods. Perhaps you have better ideas. :)
