### ISSUE TITLE
Adding mind map for Mixed Reality

### ISSUE THREAD

**Issue by FleetAdmiral** [nikitavoloboev/learn-anything#1065]
Cover basics of vision and tracking, and will also include a tutorial on developing with the hololens!

**Comment by nikitavoloboev** [comment]
Thank you. Yeah I will add the mixed reality with next update and we can include resources that you think will be great then. :)

**Comment by nikitavoloboev** [comment]
I added mixed reality. Let me know if you want to add anything there. :)
