### ISSUE TITLE
Include nodeschool.io

### ISSUE THREAD

**Issue by alisyedsadiq** [nikitavoloboev/learn-anything#1066]
Hi! Please Include learn-you-node npm package. It's really nice to learn basics of javascript on server side. thanks. it's link is https://nodeschool.io/

**Comment by alisyedsadiq** [comment]
it's already there but only learn-you-node. not complete node-school include complete nodeschool.io. #

**Comment by nikitavoloboev** [comment]
What do you mean @alisyedsadiq 

I have node school included in node.js map :)
