### ISSUE TITLE
Expanding the Literature Mind Map

### ISSUE THREAD

**Issue by sethwilsonUS** [nikitavoloboev/learn-anything#1067]
I'd like to flesh out the Literature mind map. I have some ideas for doing so, but I wanted to seek some design guidance from the community first.

One option is to break literature down by language/region, i.e. English literature, francophone literature, etc. The other option is to break it down by period/movement, i.e. Classical, Medieval, Romanticism. I guess what I'm trying to figure out is how to deal with connections that aren't purely hierarchical. For example, Romanticism is a literary movement that influenced literature in several languages--English, French, German, etc. Moreover as a movement Romanticism isn't even confined to just literature, but has implications in art, philosophy, and music.

So, for that example, it'd be possible to create a Romanticism node under Literature, Art, and Music. Or just have one main Romanticism mind map that branches off into the disciplines, but ideally somehow links into them too.

Thanks for any advice or help thinking this through! I'm new to the open source world.

**Comment by nikitavoloboev** [comment]
Thank you a lot @sethwilsonUS 

I think personal it would be best to break it down by period/movement. Perhaps we can have these periods in [history of art](https://learn-anything.xyz/history/art_history) and from there we can branch into different periods and movements and then link to appropriate works of art. What do you think?

**Comment by nikitavoloboev** [comment]
If you wish you can submit a PR with the changes to the Art section or best we can discuss it in our [Slack](https://knowledge-map.slack.com/shared_invite/MTgxNTYzMjIzNjM5LTE0OTQzMzA4MDAtYzY1YWY0ZDc0NQ) as contribution process is still not super easy.
