### ISSUE TITLE
Is there an API for this?

### ISSUE THREAD

**Issue by Tyrrrz** [nikitavoloboev/learn-anything#1181]
I want to query the knowledge base externally, for example through a bot. Is there an open API available?

**Comment by nglgzz** [comment]
At the moment you can get the JSON files and thumbnails from a given link, by prepending maps/ or thumbs/ to the link.

For instance if you have `https://learn-anything.xyz/linguistics` you can use `https://learn-anything.xyz/maps/linguistics` to get the map as JSON and `https://learn-anything.xyz/thumbs/linguistics` to get the thumbnail (thumbnails may not be always up to date though).

For search we need to find another solution for our DB first.

**Comment by nglgzz** [comment]
Also if you need to render maps on another page you can have a look at [learn-anything/react-mindmap](https://github.com/learn-anything/react-mindmap)

**Comment by Tyrrrz** [comment]
Looks like I decided to check at the wrong time 😛 
![2017-07-13 09_59_08-https___learn-anything xyz_maps_linguistics](https://user-images.githubusercontent.com/1935960/28154229-f45ddc7e-67b1-11e7-9069-8e96acbc355a.png)

**Comment by nglgzz** [comment]
Should be up now!

**Comment by Tyrrrz** [comment]
`https://learn-anything.xyz/maps/linguistics` suits my needs perfectly. Thanks!
