### ISSUE TITLE
Can't use now?

### ISSUE THREAD

**Issue by zhangpengGenedock** [nikitavoloboev/learn-anything#1182]
![image](https://user-images.githubusercontent.com/28701598/28064570-ca3be9f4-6667-11e7-8fc4-ac14636b8300.png)

when i hit enter key, nothing shows.

![image](https://user-images.githubusercontent.com/28701598/28064590-d79ffcb6-6667-11e7-9a50-e0faa808b633.png)

**Comment by nikitavoloboev** [comment]
Sorry about this, will be fixed very soon.

**Comment by nikitavoloboev** [comment]
It is up now 🚀

**Comment by zhangpengGenedock** [comment]
Awesome, but expect stable!

**Comment by zhangpengGenedock** [comment]
Can't use again?
