### ISSUE TITLE
webvr

### ISSUE THREAD

**Issue by grigb** [nikitavoloboev/learn-anything#1185]
I'm not sure how it fits into the current map for virtual reality. WebVR is an API that's supported by browsers (Chrome for Android, Firefox Nightly, Samsung Internet, Microsoft Edge, Chromium, Servo and Oculus Carmel) and frameworks like A-Frame.

https://en.wikipedia.org/wiki/WebVR

**Comment by nglgzz** [comment]
I'm gonna add a few useful links too:
- [information about web VR](https://webvr.info/)
- [subreddit for web VR](https://www.reddit.com/r/WebVR/)
- [React  VR](https://facebook.github.io/react-vr/)
- [web VR demos](https://aframe.io/)

**Comment by nikitavoloboev** [comment]
Added it, should be up in the next update. :)
