### ISSUE TITLE
Overlapping nodes in Version Control mindmap

### ISSUE THREAD

**Issue by ldahleen54** [nikitavoloboev/learn-anything#1186]
The nodes are overlapping  and it's difficult to read
![image](https://user-images.githubusercontent.com/7695881/28468890-fdf07280-6df9-11e7-8b3d-5115b78e5491.png)

**Comment by nikitavoloboev** [comment]
We will try fix this once we release a visual editor. As everyone can move the nodes then and submit changes.

**Comment by nikitavoloboev** [comment]
I will close this as it is an issue with [react mindmap](https://github.com/learn-anything/react-mindmap). We hope to fix it soon.
