### ISSUE TITLE
There's a bug when i use the site in MS Edge

### ISSUE THREAD

**Issue by Ayman97** [nikitavoloboev/learn-anything#1192]
When I searched about something. The map didn't show up.
The site was tested in Edge on two computers and the both have the same problem.
And when I've tested it on Firefox and chrome everything is fine. 
What's the problem?

**Comment by nikitavoloboev** [comment]
It is a [bug](https://github.com/learn-anything/search-engine/issues/54). We hope to fix it soon. :)

**Comment by Ayman97** [comment]
Thanks 👍 @nikitavoloboev
