### ISSUE TITLE
Search bar displays random entry after pressing Enter

### ISSUE THREAD

**Issue by dhcodes** [nikitavoloboev/learn-anything#1197]
If you search for something (ex. Cooking) that has an entry, and press Enter, the mindmap will correctly display that entry but the search bar will display a suggestion for something else. I believe the search bar should display the keyword that was searched.

**Comment by nikitavoloboev** [comment]
That is actually intended behaviour. 

Our thinking behind this decision was that we want to encourage searching of new and interesting things. So you search for something, we provide you the map but also provide you with a suggestion for what else you can search. 🙂

**Comment by dhcodes** [comment]
Interesting. I wondered if it might be. It just seems like a bug. I wonder if it could be better communicated that this is a new suggestion; perhaps by also adding "Search: <new term>" or something basic like that. I will close this though since it's intended.
