### ISSUE TITLE
add interesting research papers on computer vision

### ISSUE THREAD

**Issue by nikitavoloboev** [nikitavoloboev/learn-anything#371]
Which cannot already be found [here](https://my.mindnode.com/1s3BTU77vpBFvXWr1UfG5MkusWUGenZbqpeAAmA9)

**Comment by samuelshih** [comment]
http://ai.stanford.edu/~acoates/papers/coatesleeng_aistats_2011.pdf

Interesting paper about how using weaker classifiers (kmeans) can get comparable results to more sophisticated ones like deep neural nets with the decisions made before training a model like statistical whitening, picking a large number of features, etc.

**Comment by nikitavoloboev** [comment]
Hey @samuelshih . Thank you a lot. I have added it. Will soon release a really awesome repo with all the research papers.

**Comment by nikitavoloboev** [comment]
[Here](https://github.com/learn-anything/research-papers) is the repository. If you want to improve it, that would be lovely. 💙

**Comment by samuelshih** [comment]
@nikitavoloboev can't push my branch to make a PR, do you prefer a PR from fork?

**Comment by nikitavoloboev** [comment]
a fork is welcome, just make sure the research paper is correct category ideally, if there is not one, you can create it ❤️
