### ISSUE TITLE
Open to reddit

### ISSUE THREAD

**Issue by Astumed** [nikitavoloboev/learn-anything#745]
Since there's a subreddit for everything, you should put it on every entry if the user of the knowledge map have a question about the entry that isn't responded in the website of the entry.

**Comment by nikitavoloboev** [comment]
Thank you @Astumed. I had the same idea and was planning to do that. For example, I did it [here](https://my.mindnode.com/uFiw9mUYxyQjTnTcHqpX8VGsH5sSVSWztpY5AyWJ).

**Comment by Astumed** [comment]
Great, hope to see that more developped in the future :)

**Comment by nikitavoloboev** [comment]
Me too. :) 

If you want. You can join [our slack](https://knowledge-map.slack.com/shared_invite/MTgxNTYzMjIzNjM5LTE0OTQzMzA4MDAtYzY1YWY0ZDc0NQ). 💙
