### ISSUE TITLE
Missing topic: Optics

### ISSUE THREAD

**Issue by Yurlungur** [nikitavoloboev/learn-anything#937]
Optics is a subtopic in physics. The core principles are linear algebra, calculus, electromagnetism, and basic quantum mechanics.

**Comment by nikitavoloboev** [comment]
Thank you so much @Yurlungur. Will add it now.

**Comment by nikitavoloboev** [comment]
We have [added optics](https://learn-anything.xyz/physics/optics). :)

If you want to improve it, [please do](https://github.com/nikitavoloboev/learn-anything/issues/943). 💙
