### ISSUE TITLE
Side-Connections between topics?

### ISSUE THREAD

**Issue by Yurlungur** [nikitavoloboev/learn-anything#938]
One great thing about knowledge is that it's all very inter-connected. I notice these maps tend to be quite linear, or at least tree-like. It might be nice to have a way to explore related topics or to see them in the map.

Also I imagine people will sometimes search for SUBTOPICS and expect the search engine to figure it out. For instance, LIGO just detected gravitational waves from a black hole merger (the third detection). If I wanted to know what I needed for that, I might type in `gravitational waves` only to find a stub. I should get redirected to general relativity (for example).

**Comment by nikitavoloboev** [comment]
Yeah, we plan to integrate that soon. We currently are focusing on a new mind map renderer but after that, we will try to make search smarter. :)
