### ISSUE TITLE
Tip: Check out metacademy

### ISSUE THREAD

**Issue by Alok** [nikitavoloboev/learn-anything#939]
IMO, Metacademy has a better visual display of different topics, plus you can mark what you've learned.

One feature I've wanted to add to it is a "fringe": given a set of topics marked as "learned", tell you what you already have the prerequisites to learn next.

**Comment by nikitavoloboev** [comment]
I really love Metacademy and in many ways it inspired me to do this project. I especially love their idea of solving 'knowledge dependencies' which is what we are trying to solve here too. We will soon do it by adding 'prerequisite knowledge' to mind maps that need it. For example machine learning may have 'linear algebra' and 'statistics' shown as needed knowledge and links to them will be provided too so users don't waste time searching for resources and just learn.

I've borrowed quite a lot of things from Metacademy and have a few links pointing to the website too from this search. Metacademy however focuses on machine learning and mathematics, here we try to cover all areas.

**Comment by Alok** [comment]
If you can add the fringe feature, you'll have my eternal gratefulness.
