### ISSUE TITLE
Please make breadcrumbs clickable

### ISSUE THREAD

**Issue by triska** [nikitavoloboev/learn-anything#940]
For instance, on the [**Prolog node**](https://learn-anything.xyz/programming/programming_languages/prolog), we see the following path that leads to the&nbsp;node:

programming &rightarrow; programming&nbsp;languages &rightarrow; prolog

If possible, please make these ancestor nodes clickable, i.e.:

[programming](https://learn-anything.xyz/programming) &rightarrow; [programming&nbsp;languages](https://learn-anything.xyz/programming/programming_languages) &rightarrow; [prolog](https://learn-anything.xyz/programming/programming_languages/prolog)

Thank you!

**Comment by nikitavoloboev** [comment]
Hey @triska, we were actually to implement it too. :) 

I [opened an issue with it](https://github.com/learn-anything/search-engine/issues/29) if you or anyone wants to help us add it. Currently we are moving our mind map render to D3.js for smoother User Experience but I will look into this issue. Hopefully it will be added soon. 💙

**Comment by nikitavoloboev** [comment]
The path is clickable now @triska. I hope you like it. :)

**Comment by triska** [comment]
Awesome, thank you!

Also, I noted the following:

[programming&nbsp;languages](https://learn-anything.xyz/programming/programming_languages) clearly displays:

logic&nbsp;programming&rightarrow;**prolog**.

However, clicking on "logic&nbsp;programming" leads to: http://www.wikiwand.com/en/Logic_programming.

Instead, I would rather like to be taken to [**logic&nbsp;programming**](https://learn-anything.xyz/programming/programming_paradigms/logic_programming)!

Also, this same structure (logic&nbsp;programming&rightarrow;prolog) should also show up there!

Confusingly, there seem to be 3 different navigational concepts here:

1. the node correctly displays related concepts
2. but, clicking on other nodes takes me to their *wiki* pages
3. the "actual" nodes do not share the same structure that is suggested in&nbsp;(1).

Please consider unifying the navigation to make it more predictable. Thank&nbsp;you!

**Comment by nikitavoloboev** [comment]
Yes, you are right. If a map exists for a concept, a link to map is provided, if not a wiki is usually provided as it is often the best source of info.

I just recently added logic programming so didn't yet change the link in programming but I will now, same for functional programming. :) 

What do you think of this structure?

**Comment by triska** [comment]
Thank you! However, from what I can tell, "Prolog" still does not appear at https://learn-anything.xyz/programming/programming_paradigms/logic_programming.

However, it *does* appear at:

https://my.mindnode.com/DRHzPabqxynXg22yn4qyossXjbdx8y8sVZkWNmjx

So, there is even a form of navigation that is completely distinct from the actual site? Why is this not synchronized?

**Comment by nikitavoloboev** [comment]
Yeah all maps reside in mindnode currently. We fetch all maps and render them ourselves for our search engine but there is a delay between the updates.

We are moving to a new system which both eases contributions.
